[package]
name = "snap"
version = "0.1.1"
edition = "2024"
description = "Screenshot tool — nopeekOS."

[lib]
crate-type = ["cdylib"]

[dependencies]
nopeek_widgets = { path = "../sdk/widgets" }
miniz_oxide = { version = "0.9", default-features = false, features = ["with-alloc"] }

[build-dependencies]
nopeek_widgets = { path = "../sdk/widgets" }

[profile.release]
opt-level = "s"
lto = true
strip = true
