//! Bundled asset list — embedded only in the installer kernel.
//!
//! build.sh stages every asset (font, WASM modules + their .version
//! files) from `release/` into `kernel/src/install_data/assets/`
//! before Pass 2 of the installer build. Pass 2 compiles with
//! `--features installer`, which activates the `#[cfg]`-gated
//! `include_bytes!` / `include_str!` calls below.
//!
//! Normal kernel builds (without the installer feature) omit this
//! module entirely — zero bytes bundled, zero size cost.
//!
//! Runtime flow (`install::install_to_nvme`):
//!   1. Partition NVMe, format ESP, write GRUB + kernel.bin.
//!   2. npkfs::mkfs + mount.
//!   3. Iterate BUNDLED_ASSETS, write each entry to npkFS:
//!      - always store `<fs_path>` with the bytes
//!      - if version Some, also store `<fs_path>.version` — so
//!        `intent::install` and `intent::install::plan_modules`
//!        see the module as up-to-date and skip spurious redownloads.
//!   4. First boot from NVMe: FS is seeded, font + modules are ready.
//!
//! Sig verification is skipped for bundled assets: the installer
//! kernel itself is ECDSA P-384 signed (OTA trust chain), and the
//! bytes are inside its binary. An attacker who controls the
//! installer kernel already controls its embedded data. OTA-path
//! (`intent::install`) still verifies signatures for runtime updates.

#![cfg(feature = "installer")]

/// One bundled asset — filesystem path it lands under in npkFS, plus
/// the embedded bytes. For WASM modules, `version` carries the string
/// that will also be stored at `<fs_path>.version`.
pub struct BundledAsset {
    pub fs_path: &'static str,
    pub bytes:   &'static [u8],
    /// Version string (a semver line ending in "\n"), or None for
    /// non-versioned assets like fonts. If Some, we also write
    /// `<fs_path>.version` into npkFS so update/install checks see the
    /// right version.
    pub version: Option<&'static str>,
}

/// Assets shipped with the installer. Extend this list when new
/// system fonts or first-party WASM modules become part of the
/// default install.
///
/// Paths follow the npkFS convention `sys/<category>/<name>`.
/// The wallpapers a fresh install starts with. `fs_path` is the bare file
/// name: they go straight into the user's `pictures/wallpapers/` and are
/// theirs from then on — no system copy, and `update` never touches them.
///
/// Generated by build.sh Pass 1 from `assets/wallpapers/` (`include_bytes!`
/// needs a literal name).
include!("wallpapers.rs");

/// Everything the installer seeds into `sys/`.
pub fn bundled() -> impl Iterator<Item = &'static BundledAsset> {
    BUNDLED_ASSETS.iter()
}

pub static BUNDLED_ASSETS: &[BundledAsset] = &[
    // ── System UI font ────────────────────────────────────────────
    BundledAsset {
        fs_path: "sys/fonts/inter-variable",
        bytes:   include_bytes!("inter-variable.ttf"),
        version: None,
    },
    // Monospace face — `TextStyle::Mono` (clock, file-size columns,
    // source code). Unmodified IBM Plex Mono Regular.
    BundledAsset {
        fs_path: "sys/fonts/ibm-plex-mono",
        bytes:   include_bytes!("ibm-plex-mono.ttf"),
        version: None,
    },
    // Both faces are SIL Open Font License 1.1, which requires the
    // licence to accompany every copy of the font — including the ones
    // inside an installed system. Planted next to them, not just kept in
    // the source tree.
    BundledAsset {
        fs_path: "sys/fonts/LICENSE-Inter",
        bytes:   include_bytes!("LICENSE-Inter.txt"),
        version: None,
    },
    BundledAsset {
        fs_path: "sys/fonts/LICENSE-IBM-Plex",
        bytes:   include_bytes!("LICENSE-IBM-Plex.txt"),
        version: None,
    },

    // ── Phosphor icon atlas ───────────────────────────────────────
    BundledAsset {
        fs_path: "sys/icons/phosphor",
        bytes:   include_bytes!("phosphor.atlas"),
        version: None,
    },

    // ── MicroVM Linux bzImage ─────────────────────────────────────
    // Alpine linux-virt kernel, extracted from the apk's
    // boot/vmlinuz-virt and placed in release/assets/.
    // Loaded on demand by `microvm linux` via npkfs::fetch.
    BundledAsset {
        fs_path: "sys/microvm/linux-virt.bzImage",
        bytes:   include_bytes!("linux-virt.bzImage"),
        version: None,
    },

    // ── MicroVM initramfs ─────────────────────────────────────────
    // Rust PID-1 from microvm/linux/init/ packed as newc-cpio + gzip.
    // Loaded by `microvm linux` alongside the bzImage; Linux mounts
    // it at /, exec's /init.
    BundledAsset {
        fs_path: "sys/microvm/initramfs.cpio.gz",
        bytes:   include_bytes!("microvm-initramfs.cpio.gz"),
        version: None,
    },


    // ── First-party WASM modules ──────────────────────────────────
    // Keep in sync with release/modules/ output of build.sh release.
    BundledAsset {
        fs_path: "sys/wasm/top",
        bytes:   include_bytes!("top.wasm"),
        version: Some(include_str!("top.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/debug",
        bytes:   include_bytes!("debug.wasm"),
        version: Some(include_str!("debug.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/wallpaper",
        bytes:   include_bytes!("wallpaper.wasm"),
        version: Some(include_str!("wallpaper.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/drun",
        bytes:   include_bytes!("drun.wasm"),
        version: Some(include_str!("drun.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/dock",
        bytes:   include_bytes!("dock.wasm"),
        version: Some(include_str!("dock.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/bar",
        bytes:   include_bytes!("bar.wasm"),
        version: Some(include_str!("bar.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/loft",
        bytes:   include_bytes!("loft.wasm"),
        version: Some(include_str!("loft.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/testdisk",
        bytes:   include_bytes!("testdisk.wasm"),
        version: Some(include_str!("testdisk.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/spell",
        bytes:   include_bytes!("spell.wasm"),
        version: Some(include_str!("spell.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/pick",
        bytes:   include_bytes!("pick.wasm"),
        version: Some(include_str!("pick.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/iris",
        bytes:   include_bytes!("iris.wasm"),
        version: Some(include_str!("iris.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/snap",
        bytes:   include_bytes!("snap.wasm"),
        version: Some(include_str!("snap.version")),
    },
    BundledAsset {
        fs_path: "sys/wasm/beak",
        bytes:   include_bytes!("beak.wasm"),
        version: Some(include_str!("beak.version")),
    },

    // ── MicroVM userspace bundle (LibreWolf) ──────────────────────
    // Optional: only baked in when built with the `bundle-userspace`
    // cargo feature (set by `./build.sh usb-full` /
    // `qemu-installer-full`). Otherwise the bundle is fetched via
    // OTA from GitHub Releases on the first `update` post-install.
    //
    // Path lines up with what PID-1 looks for at boot (sys/microvm/
    // userspace.sqfs); npkFS-store on install seeds it directly, no
    // network round-trip needed → browser ready on first login.
    //
    // Future bundles (office, ide, …) plug in next to this one with
    // their own feature flag.
    #[cfg(feature = "bundle-userspace")]
    BundledAsset {
        fs_path: "sys/microvm/userspace.sqfs",
        bytes:   include_bytes!("microvm-userspace.sqfs"),
        version: None,
    },
];

/// Stub invoked by install.rs to avoid conditional compilation at the
/// call site. Writes every bundled asset into npkFS. Must only run
/// after `npkfs::mount` has succeeded and the disk key is set;
/// otherwise data lands as plaintext.
pub fn bootstrap_into_npkfs() {
    use crate::kprintln;
    use crate::security::capability::CAP_NULL;

    crate::kprintln!("[npk] Seeding npkFS with {} bundled asset(s)...", BUNDLED_ASSETS.len());
    let mut total_bytes: usize = 0;
    for a in bundled() {
        match crate::npkfs::store(a.fs_path, a.bytes, CAP_NULL) {
            Ok(_) => {
                total_bytes += a.bytes.len();
                kprintln!("[npk]   {} ({} bytes)", a.fs_path, a.bytes.len());
            }
            Err(e) => {
                kprintln!("[npk]   FAILED: {} — {:?}", a.fs_path, e);
                continue;
            }
        }

        // Versioned asset → also write the `.version` sidecar so
        // `intent::install` / `intent::install::plan_modules`
        // recognise it as installed at the right version.
        if let Some(version) = a.version {
            let ver_path = alloc::format!("{}.version", a.fs_path);
            if let Err(e) = crate::npkfs::store(&ver_path, version.as_bytes(), CAP_NULL) {
                kprintln!("[npk]   FAILED (version): {} — {:?}", ver_path, e);
            }
        }

    }
    kprintln!("[npk] Seeded {} bytes total.", total_bytes);

    seed_wallpapers();
}

/// Put the bundled wallpapers into `home/<user>/pictures/wallpapers/` —
/// the folder `wallpaper list` and the boot pick read. Reads the user name
/// written moments earlier by setup. An existing file is left alone.
fn seed_wallpapers() {
    use crate::kprintln;
    use crate::security::capability::CAP_NULL;

    let user = match crate::config::get("name") {
        Some(n) if !n.is_empty() => n,
        _ => return,
    };
    for a in WALLPAPERS {
        let target = alloc::format!("home/{}/pictures/wallpapers/{}", user, a.fs_path);
        if crate::npkfs::exists(&target) { continue; }
        match crate::npkfs::store(&target, a.bytes, CAP_NULL) {
            Ok(_)  => kprintln!("[npk]   {}", target),
            Err(e) => kprintln!("[npk]   FAILED: {} — {:?}", target, e),
        }
    }

    // The first boot shows a chosen picture, not a random one — unless
    // someone already chose.
    if crate::config::get("wallpaper").is_none()
        && WALLPAPERS.iter().any(|a| a.fs_path == INITIAL_WALLPAPER)
    {
        crate::config::set("wallpaper",
            &alloc::format!("home/{}/pictures/wallpapers/{}", user, INITIAL_WALLPAPER));
    }
}

/// The wallpaper of a fresh install: the calmest of the set — glass reads
/// best over it in both themes.
const INITIAL_WALLPAPER: &str = "ice-cosmic-waves.png";
