[workspace]
members = ["kernel"]
exclude = [
    "tools/wasm/wallpaper",
    "tools/wasm/top",
    "tools/wasm/wifi",
    "tools/wasm/wifi_ax200",
    "tools/wasm/debug",
    "tools/wasm/sdk/widgets",
    "tools/wasm/drun",
    "tools/wasm/dock",
    "tools/wasm/bar",
    "tools/wasm/loft",
    "tools/wasm/spell",
    "tools/wasm/iris",
    "tools/wasm/snap",
    "tools/wasm/testdisk",
    "tools/wasm/aml/core",
    "tools/wasm/aml/harness",
    "tools/wasm/aml/wasm",
    "tools/regen-icons",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 2
lto = true
