[package]
name = "iris"
version = "0.2.1"
edition = "2024"
description = "Image viewer — nopeekOS."

[lib]
crate-type = ["cdylib"]

[dependencies]
nopeek_widgets = { path = "../sdk/widgets" }
miniz_oxide = { version = "0.9", default-features = false, features = ["with-alloc"] }

[dependencies.postcard]
version = "1.0"
default-features = false
features = ["alloc"]

[build-dependencies]
nopeek_widgets = { path = "../sdk/widgets" }

[profile.release]
opt-level = "s"
lto = true
strip = true
