#!/usr/bin/env python3
"""Extract rtw8852bx_pmac_ht20_mcs7_tbl from rtw8852b_common.c.

Unlike the rfk/tssi tables which use reg5_def (with flag + path), this
one is reg3_def (addr, mask, data) — plain masked writes. Emit as a
flat [(u32, u32, u32)] array in src/bb_tables.rs.
"""
import re
from pathlib import Path

SRC = "/tmp/linux-rtw89/drivers/net/wireless/realtek/rtw89/rtw8852b_common.c"

BIT = re.compile(r'BIT\((\d+)\)')
GM  = re.compile(r'GENMASK\((\d+),\s*(\d+)\)')

def evalnum(s):
    s = s.strip()
    while True:
        m = BIT.search(s)
        if not m: break
        s = s.replace(m.group(0), str(1 << int(m.group(1))))
    while True:
        m = GM.search(s)
        if not m: break
        h, l = int(m.group(1)), int(m.group(2))
        s = s.replace(m.group(0), str(((1 << (h - l + 1)) - 1) << l))
    return int(s, 0)

def extract(src, name):
    pat = rf'static const struct rtw89_reg3_def {name}\[\] = \{{(.*?)^\}};'
    m = re.search(pat, src, re.DOTALL | re.MULTILINE)
    if not m: raise RuntimeError(f"{name} not found")
    body = m.group(1)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.DOTALL)
    body = re.sub(r'//.*', '', body)
    ents = []
    for m in re.finditer(r'\{\s*([^,]+),\s*([^,]+),\s*([^}]+)\}', body):
        addr = evalnum(m.group(1))
        mask = evalnum(m.group(2))
        data = evalnum(m.group(3))
        ents.append((addr, mask, data))
    return ents

def main():
    text = Path(SRC).read_text()
    out = [
        "// Auto-generated by gen_pmac.py — DO NOT EDIT.",
        "// PMAC HT20 MCS7 table for TSSI alimentk test-TX.",
        "",
    ]
    for name in ["rtw8852bx_pmac_ht20_mcs7_tbl"]:
        ents = extract(text, name)
        rn = name.replace("rtw8852bx_", "").upper()
        out.append(f"pub static {rn}: &[(u32, u32, u32)] = &[")
        for a, m, d in ents:
            out.append(f"    (0x{a:X}, 0x{m:X}, 0x{d:X}),")
        out.append("];")
        out.append("")
        print(f"{name}: {len(ents)} entries")

    Path(__file__).parent.joinpath("src/bb_tables.rs").write_text("\n".join(out))

if __name__ == "__main__":
    main()
