#!/usr/bin/env python3
"""Extract IQK-related register tables from Linux rtw8852b_rfk.c → Rust.

Targets:
  - rtw8852b_set_nondbcc_path01      (iqk_macbb_setting, 32 entries)
  - rtw8852b_restore_nondbcc_path01  (iqk_afebb_restore, 18 entries)
  - rtw8852b_backup_bb_regs / backup_rf_regs (for backup/restore)

Output: src/iqk_tables.rs

Usage: ./gen_iqk.py /tmp/linux-rtw89/drivers/net/wireless/realtek/rtw89/rtw8852b_rfk.c
"""
import re
import sys
from pathlib import Path


def extract_reg3_def(src: str, name: str) -> list[tuple[int, int, int]]:
    """Extract {addr, mask, value} rows from a static const struct rtw89_reg3_def NAME[]."""
    pat = re.compile(
        rf"rtw89_reg3_def\s+{re.escape(name)}\s*\[\]\s*=\s*\{{(.*?)\}}\s*;",
        re.DOTALL,
    )
    m = pat.search(src)
    if not m:
        raise RuntimeError(f"Table {name} not found")
    body = m.group(1)
    rows = []
    for entry in re.finditer(r"\{\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*,\s*(0x[0-9a-fA-F]+)\s*\}", body):
        addr = int(entry.group(1), 16)
        mask = int(entry.group(2), 16)
        val = int(entry.group(3), 16)
        rows.append((addr, mask, val))
    return rows


def extract_u32_array(src: str, name: str) -> list[int]:
    """Extract a static const u32 NAME[] = { 0xXX, 0xYY, ... }; array."""
    pat = re.compile(
        rf"static\s+const\s+u32\s+{re.escape(name)}\s*\[\]\s*=\s*\{{(.*?)\}}\s*;",
        re.DOTALL,
    )
    m = pat.search(src)
    if not m:
        raise RuntimeError(f"Array {name} not found")
    body = m.group(1)
    return [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", body)]


def emit_reg3_table(name: str, rows: list[tuple[int, int, int]]) -> str:
    out = [f"/// Linux {name} — ({len(rows)} entries)"]
    out.append(f"pub static {name.upper()}: &[(u32, u32, u32)] = &[")
    for a, m, v in rows:
        out.append(f"    (0x{a:04x}, 0x{m:08x}, 0x{v:08x}),")
    out.append("];")
    return "\n".join(out)


def emit_u32_table(name: str, vals: list[int]) -> str:
    out = [f"/// Linux {name} — ({len(vals)} entries)"]
    out.append(f"pub static {name.upper()}: &[u32] = &[")
    for v in vals:
        out.append(f"    0x{v:04x},")
    out.append("];")
    return "\n".join(out)


def main():
    if len(sys.argv) != 2:
        print("usage: gen_iqk.py /path/to/rtw8852b_rfk.c", file=sys.stderr)
        sys.exit(1)
    src_path = Path(sys.argv[1])
    src = src_path.read_text()

    set_tbl = extract_reg3_def(src, "rtw8852b_set_nondbcc_path01")
    restore_tbl = extract_reg3_def(src, "rtw8852b_restore_nondbcc_path01")

    try:
        backup_bb = extract_u32_array(src, "rtw8852b_backup_bb_regs")
    except RuntimeError:
        backup_bb = []
    try:
        backup_rf = extract_u32_array(src, "rtw8852b_backup_rf_regs")
    except RuntimeError:
        backup_rf = []

    out_path = Path(__file__).parent / "src" / "iqk_tables.rs"
    lines = [
        "//! IQK tables extracted from Linux rtw89 driver (rtw8852b_rfk.c).",
        "//!",
        "//! Each reg3_def entry: (addr, mask, value). PHY-space registers",
        "//! require + PHY_CR_BASE (0x10000) when accessed via mmio.",
        "//!",
        "//! Generated by tools/wasm/wifi/gen_iqk.py. Do not hand-edit.",
        "",
        "#![allow(dead_code)]",
        "",
        emit_reg3_table("rtw8852b_set_nondbcc_path01", set_tbl),
        "",
        emit_reg3_table("rtw8852b_restore_nondbcc_path01", restore_tbl),
    ]
    if backup_bb:
        lines += ["", emit_u32_table("rtw8852b_backup_bb_regs", backup_bb)]
    if backup_rf:
        lines += ["", emit_u32_table("rtw8852b_backup_rf_regs", backup_rf)]
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path} — set({len(set_tbl)}), restore({len(restore_tbl)})"
          + (f", backup_bb({len(backup_bb)})" if backup_bb else "")
          + (f", backup_rf({len(backup_rf)})" if backup_rf else ""))


if __name__ == "__main__":
    main()
