#!/usr/bin/env python3
"""
Extract rtw8852b_rfk_table.c RFK tables as Rust const arrays.

Each table entry is one of:
  RTW89_DECL_RFK_WRF(path, addr, mask, data)  -> RF masked write
  RTW89_DECL_RFK_WM(addr, mask, data)         -> PHY masked write (+CR_BASE)
  RTW89_DECL_RFK_WS(addr, mask)               -> PHY set bits
  RTW89_DECL_RFK_WC(addr, mask)               -> PHY clear bits
  RTW89_DECL_RFK_DELAY(us)                    -> udelay(us)

Emit as flat u32 arrays: [flag, path, addr, mask, data] * N per table.
Flag values match Linux RTW89_RFK_F_*: WRF=0, WM=1, WS=2, WC=3, DELAY=4.
"""

import re
from pathlib import Path

LINUX_TBL = "/tmp/linux-rtw89/drivers/net/wireless/realtek/rtw89/rtw8852b_rfk_table.c"

# Only tables we actually need for DACK + RX_DCK + set_rx_dck
WANTED = [
    "rtw8852b_afe_init_defs",
    "rtw8852b_check_addc_defs_a",
    "rtw8852b_check_addc_defs_b",
    "rtw8852b_check_dadc_en_defs_a",
    "rtw8852b_check_dadc_en_defs_b",
    "rtw8852b_check_dadc_dis_defs_a",
    "rtw8852b_check_dadc_dis_defs_b",
    "rtw8852b_dack_s0_1_defs",
    "rtw8852b_dack_s0_2_defs",
    "rtw8852b_dack_s0_3_defs",
    "rtw8852b_dack_s1_1_defs",
    "rtw8852b_dack_s1_2_defs",
    "rtw8852b_dack_s1_3_defs",
]

FLAG_WRF, FLAG_WM, FLAG_WS, FLAG_WC, FLAG_DELAY = 0, 1, 2, 3, 4

RF_PATH_MAP = {"RF_PATH_A": 0, "RF_PATH_B": 1, "0": 0, "1": 1}

# Linux GENMASK / BIT helpers — crude but enough for our tables
BIT_RE = re.compile(r'BIT\((\d+)\)')
GENMASK_RE = re.compile(r'GENMASK\((\d+),\s*(\d+)\)')


def eval_numeric(expr: str) -> int:
    expr = expr.strip()
    # Replace BIT(n) and GENMASK(h,l)
    while True:
        m = BIT_RE.search(expr)
        if not m: break
        n = int(m.group(1))
        expr = expr.replace(m.group(0), str(1 << n))
    while True:
        m = GENMASK_RE.search(expr)
        if not m: break
        h, l = int(m.group(1)), int(m.group(2))
        mask = ((1 << (h - l + 1)) - 1) << l
        expr = expr.replace(m.group(0), str(mask))
    return int(expr, 0)


def extract_table(src: str, name: str):
    """Find `static const struct rtw89_reg5_def NAME[] = { ... };` and parse."""
    pat = rf'static const struct rtw89_reg5_def {name}\[\] = \{{(.*?)^\}};'
    m = re.search(pat, src, re.DOTALL | re.MULTILINE)
    if not m:
        raise RuntimeError(f"table {name} not found")
    body = m.group(1)

    # Strip comments
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.DOTALL)
    body = re.sub(r'//.*', '', body)

    # Each entry on its own (may span lines), comma-separated at top level.
    # Simplest: match RTW89_DECL_RFK_... with balanced parens.
    entries = []
    i = 0
    while i < len(body):
        # Find next RTW89_DECL_RFK_
        j = body.find("RTW89_DECL_RFK_", i)
        if j < 0: break
        kw_end = body.find("(", j)
        kw = body[j:kw_end]  # e.g. RTW89_DECL_RFK_WM
        # Find matching closing paren
        depth = 0
        k = kw_end
        while k < len(body):
            c = body[k]
            if c == '(': depth += 1
            elif c == ')':
                depth -= 1
                if depth == 0: break
            k += 1
        args_str = body[kw_end + 1:k].strip()
        # Split by top-level commas
        args = []
        depth = 0
        cur = ""
        for c in args_str:
            if c == '(': depth += 1
            if c == ')': depth -= 1
            if c == ',' and depth == 0:
                args.append(cur.strip())
                cur = ""
            else:
                cur += c
        if cur.strip():
            args.append(cur.strip())

        if kw == "RTW89_DECL_RFK_WRF":
            key = args[0].strip()
            if key in RF_PATH_MAP:
                path = RF_PATH_MAP[key]
            else:
                path = int(key, 0)
            addr = eval_numeric(args[1])
            mask = eval_numeric(args[2])
            data = eval_numeric(args[3])
            entries.append((FLAG_WRF, path, addr, mask, data))
        elif kw == "RTW89_DECL_RFK_WM":
            addr = eval_numeric(args[0])
            mask = eval_numeric(args[1])
            data = eval_numeric(args[2])
            entries.append((FLAG_WM, 0, addr, mask, data))
        elif kw == "RTW89_DECL_RFK_WS":
            addr = eval_numeric(args[0])
            mask = eval_numeric(args[1])
            entries.append((FLAG_WS, 0, addr, mask, 0))
        elif kw == "RTW89_DECL_RFK_WC":
            addr = eval_numeric(args[0])
            mask = eval_numeric(args[1])
            entries.append((FLAG_WC, 0, addr, mask, 0))
        elif kw == "RTW89_DECL_RFK_DELAY":
            us = eval_numeric(args[0])
            entries.append((FLAG_DELAY, 0, 0, 0, us))

        i = k + 1

    return entries


def main():
    text = Path(LINUX_TBL).read_text()
    out = ["// Auto-generated by gen_rfk.py from rtw8852b_rfk_table.c",
           "// Format: flat u32 arrays of (flag, path, addr, mask, data) per entry.",
           "// Flags: 0=WRF, 1=WM, 2=WS, 3=WC, 4=DELAY",
           ""]
    for name in WANTED:
        entries = extract_table(text, name)
        out.append(f"pub static {name.upper()}: &[(u8, u8, u32, u32, u32)] = &[")
        for (flag, path, addr, mask, data) in entries:
            out.append(f"    ({flag}, {path}, 0x{addr:X}, 0x{mask:X}, 0x{data:X}),")
        out.append("];")
        out.append("")
        print(f"{name}: {len(entries)} entries")

    Path("src/rfk_tables.rs").write_text("\n".join(out))


if __name__ == "__main__":
    main()
